# Generated by Django 5.1.7 on 2025-04-10 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
    ]
