# Generated by Django 5.1.7 on 2025-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Books', 'Books'), ('Sports', 'Sports'), ('Automotive', 'Automotive'), ('Toys', 'Toys'), ('Health', 'Health'), ('Collectibles', 'Collectibles'), ('Others', 'Others')], max_length=64),
        ),
    ]
